### ISSUE TITLE
Display response

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/old-query-tool#10]
Given a query result list received from BagelAPI, we want a component that can display visually some basic information about each result dataset object.

- [x] Default view before results are available that indicates how to run a query
- [x] A view If no results are returned (i.e. list is empty)

When a non-empty query is returned display:
- [x] A select all option
- [x] Summary stats
- [x] Download results button
- [x] File download functionality 

For each dataset in the response display a:
- [x] Card
- [x] Dataset title
- [x] Number of subjects
- [x] Modalities toolbar on cards

Test
- [x] default view
- [x] No result view
- [x] Select all functionality: Whether it selects and unselects all checkboxes and updates `download` correctly
- [x] A card displayed for each dataset returned
- [x] Cards display the correct dataset title, number of subjects, and modalities
- [x] Summary stats
- [x] Download results button functionality sync with checkboxes
- [x] `update-download` event is emitted

**Comment by rmanaem** [comment]
@surchs 
I don't think we've discussed the download results file:
- which properties of the response object should be in the file?
- How should the file be structured?

> which properties of the response object should be in the file?

I believe we want the `dataset_name`, `num_matching_subjects`, and `file_paths`

> How should the file be structured?

`.csv` file with `dataset, number of matching subjects, and subject file paths` as `headers`, 3 columns and a row for each dataset

**Comment by surchs** [comment]
Good point @rmanaem. I think the simplest solution would be to just download the whole JSON you got from the API. That'd probably not be very functional, but we could start there. If you go with `.csv` directly (good idea I think), then I would add one row per path with the headers you mentioned (dataset name, # subjects matching, path). The next step up from that would be to let the user choose what datasets should be included in the downloaded .csv via some UI element. I think this last point should probably happen in cycle 2 unless it is very easy to do

**Comment by rmanaem** [comment]
@surchs 
> The next step up from that would be to let the user choose what datasets should be included in the downloaded .csv via some UI element. 

Do you mean select them using the checkboxes?

**Comment by surchs** [comment]
I think that would make sense, that's what the demo had.
edit: based on the issue description we didn't plan to have this "I can select the datasets for which I want to download data" functionality in this cycle. So let's not add it now.

**Comment by rmanaem** [comment]
Yea that's already implemented, let me push what I have and you can take a look.

**Comment by rmanaem** [comment]
Checkout [feat-10](https://github.com/neurobagel/query-tool/tree/feat-10)

**Comment by surchs** [comment]
Can you make a (draft) PR for this please
